name:                CEREScript-SS
version:             0.20.0.0
github:              "HolosDev/CEREScript-SS"
license:             OtherLicense
author:              "YongJoon Joe"
maintainer:          "Holos Works <developer@holos.dev>"
copyright:           "2019-2020 Holos Works / PPUZZL Group"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/HolosDev/CEREScript-SS#readme>

dependencies:
- base >= 4.7 && < 5
- text
- containers
- text-show
- text-show-instances
- vector

default-extensions:
- OverloadedStrings

library:
  source-dirs: src

tests:
  Test-Spec:
    main:                Spec.hs
    source-dirs:
    - test
    - tests/Spec
    default-extensions:
    - TemplateHaskell
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CEREScript-SS
    - HUnit
    - QuickCheck
    - silently
    - test-framework
    - test-framework-hunit
    - test-framework-quickcheck2
    - test-framework-th
    - call-stack
    - containers
