name:                CEREScript-Core
version:             0.2.0.0
github:              "MiRiS-Project/CEREScript-Core"
license:             OtherLicense
author:              "MiRiS Project"
maintainer:          "YongJoon Joe <developer@miris-project.net>"
copyright:           "2019 MiRiS Project"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/MiRiS-Project/CEREScript-Core#readme>

dependencies:
- base >= 4.7 && < 5
- text
- containers
- text-show

default-extensions:
- OverloadedStrings

library:
  source-dirs: src

executables:
  CEREScript-Core-Basic-Interpreter-exe:
    main:                Main.hs
    source-dirs:         apps/BasicInterpreter
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CEREScript-Core
    - splitmix
  Example-Tx-exe:
    main:                Main.hs
    source-dirs:         examples/Tx
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CEREScript-Core
    - splitmix

tests:
  CEREScript-Core-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CEREScript-Core
    - HUnit
    - QuickCheck
    - silently
    - test-framework
    - test-framework-hunit
    - test-framework-quickcheck2
    - test-framework-th
    - call-stack
    - containers
