name:                CEREScript-Core01
version:             0.5.3.0
github:              "MiRiS-Project/CEREScript-Core01"
license:             OtherLicense
author:              "MiRiS Project"
maintainer:          "YongJoon Joe <developer@miris-project.net>"
copyright:           "2019-2020 MiRiS Project"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/MiRiS-Project/CEREScript-Core01#readme>

dependencies:
- base >= 4.7 && < 5
- text
- containers
- text-show

default-extensions:
- OverloadedStrings

library:
  source-dirs: src

tests:
  Test-Spec:
    main:                Spec.hs
    source-dirs:
    - test
    - tests/Spec
    default-extensions:
    - TemplateHaskell
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - CEREScript-Core01
    - HUnit
    - QuickCheck
    - silently
    - test-framework
    - test-framework-hunit
    - test-framework-quickcheck2
    - test-framework-th
    - call-stack
    - containers
