resolver: lts-14.27

packages:
- .
# In development
#- /AoDw/CEREScript/ArchCEREScript

extra-deps:
# In public
#- github: HolosDev/ArchCEREScript
#- git: https://gitlab.com/holosdev/ArchCEREScript
#  commit: 88519609a5b06a1dc7842904f1b4163fc0ca22d2
